version: '3.7'

services:
  postgresdatabase:
    image: "postgres:11-alpine"
    environment:
     POSTGRES_PASSWORD: Postgres@123
     POSTGRES_DB: Employee

    ports:
      - '5432:5432'  
    volumes:
      - postgres_data:/Library/PostgreSQL/13/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s 
      retries: 3
  web:
    build: .
    command: sh -c " python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" 
    volumes:
      - Assignment5:/Assignment5
    ports:
      - '8000:8000'
    environment:
     POSTGRES_HOST: postgresdatabase
     POSTGRES_PASSWORD: Postgres@123
    depends_on:
     postgresdatabase:
      condition: service_healthy

volumes:
  postgres_data:
  Assignment5: