# Generated by Django 3.2.7 on 2021-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=3)),
                ('salary', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=40)),
            ],
        ),
    ]
